name: randip
version: 1.2.9-snap
summary: RandIP
description: |
  RandIP is a python script that generates random IP's |
  in an attampt to detect random servers across the |
  vast IoT.

grade: stable
confinement: strict
type: app

architectures:
  - build-on: amd64
    run-on: amd64

parts:
  randip:
    plugin: python
    python-version: python2
    source: https://github.com/blmvxer/randip.git
    stage-packages:
      - python-paramiko
      - python-stem
      - python-requests
    randip_nim:
      plugin: dump
      source: snap/
      override_build: |
      snapcraftctl build
      chmod +x randip_nim
      

    

apps:
  randip:
    command: python /snap/randip/current/snap/randip.py
    plugs:
      - network
      - network-bind
      - network-control
      - network-manager
      - network-observe
      - ssh-keys
      - ssh-public-keys
