name: randip
version: 1.2.4
summary: RandIP
description: |
  RandIP is a python script that generates random IP's |
  in an attampt to detect random servers across the |
  vast IoT.

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
    run-on: amd64

parts:
  randip:
    plugin: python
    python-version: python2
    source: https:github.com/blmvxer/randip.git
    stage-packages:
      - python-paramiko
      - python-stem
      - python-requests

apps:
  randip:
    command: python /snap/randip/current/snap/randip.py
