name: randip
version: 1.2.4
summary: RandIP
description: |
  RandIP is a python script that generates random IP's |
  in an attampt to detect random servers across the |
  vast IoT.

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
    run-on: [i386, amd64]

parts:
  randip:
    plugin: python
    python-version: python2
    source: .
    stage-packages:
      - python-paramiko
      - python-stem
      - python-requests

apps:
  randip:
    command: /usr/bin/randip
