name: randip
version: git
summary: RandIP
description: |
  RandIP is a python script that generates random IP's |
  in an attampt to detect random servers across the |
  vast IoT.

confinement: devmode

architectures: [i386, amd64]

parts:
  randip:
    plugin: python
    python-version: python2
    source: .
    stage-packages:
      - python-paramiko
      - python-stem
      - python-requests

apps:
  randip:
    command: bin/randip
